### ISSUE TITLE
the authentication is not running

### ISSUE THREAD

**Issue by ajay1706** [makkhay/FirebaseAI-Android-Chat-App#2]
It shows weak password or email id exists every time

**Comment by makkhay** [comment]
Hey, Ajay because you need to sign up for firebase and add your own google JSON file. I have removed my JSON file because of security reasons.

**Comment by ajay1706** [comment]
I added it

**Comment by ajay1706** [comment]
I do added the google JSON file in the app folder.

**Comment by makkhay** [comment]
Did you enable email sign-in option on firebase console?

**Comment by ajay1706** [comment]
oh no i guess, where it is in firebase?

**Comment by ajay1706** [comment]
yeah got it thanks

**Comment by ajay1706** [comment]
But, where is all the data is stored in the firebase?

**Comment by makkhay** [comment]
Go to authentication tab on Firebase console and you will see the registered users.

**Comment by ajay1706** [comment]
where is the data of the chat stored?

**Comment by makkhay** [comment]
Realm is helping the persistent data. Google Realm for more info

**Comment by ajay1706** [comment]
can we have a look over the data we have typed in?
